# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9e845f45761968f3f231450cf452d4cac74edcabd55357114f7290a96b77e835cc506f6fbca5017005e3dca28ef0fcb121f6ceff485be9699616e729c7b1ce6

test:
  secret_key_base: 32ca181220b70d8af488b3d794948d471e1f0554d81621114eb49d6c9a917c41b2be9b765fc1455643d780e05002ef50789b89997ba34399d6a6c66df6050ceb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
